// Generates src/db/schema.ts (the Kysely Database interface) by introspecting the
// leitura-db gateway's INFORMATION_SCHEMA. Run locally with `yarn gen:schema`.
// The output is committed and treated as read-only — never hand-edit it.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DB = process.argv[2] ?? "DBOAB";
const OUT = resolve(ROOT, "src/db/schema.ts");

function loadDevVars() {
  const raw = readFileSync(resolve(ROOT, ".dev.vars"), "utf8");
  const vars = {};
  for (const line of raw.split("\n")) {
    const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m) vars[m[1]] = m[2].replace(/\r$/, "");
  }
  return vars;
}

async function query(env, sql) {
  const url = (env.LEITURA_DB_URL || "https://leitura-db.oabpr.org.br") + "/query";
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "CF-Access-Client-Id": env.CF_ACCESS_CLIENT_ID,
      "CF-Access-Client-Secret": env.CF_ACCESS_CLIENT_SECRET,
    },
    body: JSON.stringify({ db: DB, sql, params: {} }),
  });
  if (!res.ok) throw new Error(`leitura-db ${res.status}: ${await res.text()}`);
  return (await res.json()).rows ?? [];
}

// SQL Server type -> TypeScript type. The gateway serializes rows as JSON, so
// dates/binaries come back as strings.
function tsType(sqlType) {
  const t = sqlType.toLowerCase();
  if (/(char|text|xml|uniqueidentifier)/.test(t)) return "string";
  if (/(int|numeric|decimal|real|float|money)/.test(t)) return "number"; // bigint -> number: precision risk if selected
  if (t === "bit") return "boolean";
  if (/(date|time)/.test(t)) return "string";
  if (/(binary|image)/.test(t)) return "string";
  return "unknown";
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const quoteKey = (name) => (IDENT.test(name) ? name : JSON.stringify(name));

function interfaceName(tableName, used) {
  let base = IDENT.test(tableName) ? tableName : tableName.replace(/[^A-Za-z0-9_$]/g, "_");
  if (/^[0-9]/.test(base)) base = "_" + base;
  let name = base, i = 1;
  while (used.has(name)) name = `${base}_${i++}`;
  used.add(name);
  return name;
}

const env = loadDevVars();
if (!env.CF_ACCESS_CLIENT_ID || !env.CF_ACCESS_CLIENT_SECRET) {
  console.error("Missing CF_ACCESS_CLIENT_ID / CF_ACCESS_CLIENT_SECRET in .dev.vars");
  process.exit(1);
}

console.error(`Introspecting ${DB}...`);
// The gateway caps results at 5000 rows; the full column set exceeds that, so
// page through it with OFFSET/FETCH (page < 5000 to stay under the cap).
const PAGE = 4000;
const rows = [];
for (let offset = 0; ; offset += PAGE) {
  const page = await query(
    env,
    `SELECT c.TABLE_NAME, c.COLUMN_NAME, c.DATA_TYPE, c.IS_NULLABLE, c.ORDINAL_POSITION
     FROM INFORMATION_SCHEMA.COLUMNS c
     JOIN INFORMATION_SCHEMA.TABLES t
       ON t.TABLE_NAME = c.TABLE_NAME AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
     WHERE t.TABLE_TYPE = 'BASE TABLE'
     ORDER BY c.TABLE_NAME, c.ORDINAL_POSITION
     OFFSET ${offset} ROWS FETCH NEXT ${PAGE} ROWS ONLY`,
  );
  rows.push(...page);
  if (page.length < PAGE) break;
}

const tables = new Map();
for (const r of rows) {
  if (!tables.has(r.TABLE_NAME)) tables.set(r.TABLE_NAME, []);
  tables.get(r.TABLE_NAME).push(r);
}

const used = new Set();
const ifaces = [];
const dbEntries = [];
for (const [table, cols] of [...tables].sort((a, b) => a[0].localeCompare(b[0]))) {
  const name = interfaceName(table, used);
  const body = cols
    .map((c) => {
      const t = tsType(c.DATA_TYPE);
      const nullable = c.IS_NULLABLE === "YES" ? " | null" : "";
      return `  ${quoteKey(c.COLUMN_NAME)}: ${t}${nullable};`;
    })
    .join("\n");
  ifaces.push(`export interface ${name} {\n${body}\n}`);
  dbEntries.push(`  ${quoteKey(table)}: ${name};`);
}

const out = `// This file is auto-generated by scripts/generateSchema.mjs — DO NOT EDIT.
// Regenerate with: yarn gen:schema
// Source: leitura-db / INFORMATION_SCHEMA of database ${DB} (${tables.size} tables).
/* eslint-disable */

export interface ${DB} {
${dbEntries.join("\n")}
}

${ifaces.join("\n\n")}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
console.error(`OK: ${tables.size} tables -> ${OUT}`);
